### ISSUE TITLE
Wrong reference - SMPTE ST 430-16:2014

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/st429-19#4]
SMPTE ST 430-16:2014, should be SMPTE ST 4**29**-16:2014

**Comment by palemieux** [comment]
Addressed at https://github.com/SMPTE/st429-19-private/commit/ceb69a65e1f3c3a5b7e13029fe5adc07e438f2b3

**Comment by SteveLLamb** [comment]
Approved.
